name: Build with Gradle

on:
  push:
    branches:
      - master  # 或者你使用的任何其他分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # 你可以选择其他运行环境，例如 windows-latest 或 macos-latest

    steps:
      # Checkout the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up JDK 8 (required for your project)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adoptopenjdk'

      # Cache Gradle dependencies to speed up the build process
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project with Gradle (using Gradle Wrapper)
      - name: Build with Gradle
        run: ./gradlew build

      # Optionally, run tests if you have a test task
      - name: Run tests with Gradle
        run: ./gradlew test  # 如果你有测试任务，可以启用

      # Optionally, run tasks to deploy or publish artifacts if needed
      # - name: Publish build artifacts
      #   run: ./gradlew publish

      # If your mod has additional post-processing steps, you can add them here

