name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adoptopenjdk'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Ensure gradlew has execution permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # Publish to GitHub Packages
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # The next step is disabled because the dependency graph is not enabled
    # - name: Submit Dependency Graph (optional)
    #   uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
    #   if: false  # Disable this step as Dependency Graph is disabled for your repository
